export enum HttpSuccessCode {
    OK = 'OK',
    CREATED = 'CREATED',
    DELETED = 'DELETED',
    NO_CONTENT = 'NO_CONTENT'
}

export enum HttpErrorCode {
    INVALID_INPUT = 'INVALID_INPUT',
    AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
    DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
    DB_CONNECTION_ERROR = 'DB_CONNECTION_ERROR',
    INTERNAL_SEVER_ERROR = 'INTERNAL_SERVER_ERROR',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS'
}